
package com.stepavlas.restapp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientEndpoint", targetNamespace = "http://restApp.stepavlas.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientEndpoint {


    /**
     * 
     * @return
     *     returns java.util.List<com.stepavlas.restapp.Client>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://restApp.stepavlas.com/", className = "com.stepavlas.restapp.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://restApp.stepavlas.com/", className = "com.stepavlas.restapp.GetAllResponse")
    @Action(input = "http://restApp.stepavlas.com/ClientEndpoint/getAllRequest", output = "http://restApp.stepavlas.com/ClientEndpoint/getAllResponse")
    public List<Client> getAll();

}
